#%RAML 1.0 Library
types:
  FilePath:
    type: object
    properties:
      path: string
      type?:
        enum:
          - "FOLDER"
          - "FILE"
        default: "FILE"
    example: !include ../examples/file.json
  FileContents:
    type: array
    items: FileContent
  FileContent:
    type: object
    properties:
      path:
        type: string
      content:
        type: string
securitySchemes:
  myScheme:
    type: OAuth 2.0
    description: basic scheme
    settings:
      accessTokenUri: /token