#%RAML 1.0

title: test API
mediaType: application/json
types:
  airplane:
    type: object
    displayName: plane
    description: none
    default:
      a: 4
    facets:
      b?: number
    examples:
      one:
        a: 5
      two:
        a: 7
    example:
      a: 8
    xml:
      attribute: true # serialize it as an XML attribute
      name: "fullname"
    allowedTargets: [Method]
/resource:
  post:
    body:
      type: object
      displayName: plane
      description: none

      default:
        a: 4
      facets:
        b?: number
      examples:
        one:
          a: 5
        two:
          a: 7
      example:
        a: 8
      xml:
        attribute: true # serialize it as an XML attribute
        name: "fullname"
      allowedTargets: [Body]
    responses:
      201:
        body: airplane
