#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: airplane
types:
  airplane:
    type: string
    displayName: plane
    description: none
    default:
      ms20
    facets:
      b?: number
    examples:
      one:
        ms
      two:
        ab
    example:
      a
    xml:
      attribute: true # serialize it as an XML attribute
      name: "fullname"
    allowedTargets: [Method]
/resource/{airplane}:
  uriParameters:
    airplane:
      type: string
      displayName: plane
      description: none
      default:
        ms20
      facets:
        b?: number
      examples:
        one:
          ms
        two:
          ab
      example:
        a
      xml:
        attribute: true # serialize it as an XML attribute
        name: "fullname"
      allowedTargets: [Method]
  post:
    queryParameters:
      airplane:
        type: string
        displayName: plane
        description: none
        default:
          ms20
        facets:
          b?: number
        examples:
          one:
            ms
          two:
            ab
        example:
          a
        xml:
          attribute: true # serialize it as an XML attribute
          name: "fullname"
        allowedTargets: [Method]
    headers:
      A-IM:
        type: string
        displayName: plane
        description: none
        default:
          ms20
        facets:
          b?: number
        examples:
          one:
            ms
          two:
            ab
        example:
          a
        xml:
          attribute: true # serialize it as an XML attribute
          name: "fullname"
        allowedTargets: [Method]
