#%RAML 1.0
title: test

types:
  ObjectType:
    properties:
      p1:
        type: string
      p2: integer
  MyType:
    properties:
      prop1: ObjectType
      prop2: string
    example:
      prop1:
        p1:
        *
