#%RAML 1.0
version: v1
title: dataTypes

types:
  Person: !include test06-person.raml
  Person2:
    properties:
      name: string
      address: string
/manager/{id}:
  get:
    queryParameters:
      id: string
    responses:
      200:
        body:
          application/json:
            type: Person2
            example:
              name: JJ
              a*:
