#%RAML 1.0
title: test
securitySchemes:
  obasic:
    type: Basic Authentication
  oauth2:
    type: OAuth 2.0
    displayName: oauth 2
    description: Oauth 2 method
    describedBy:
      queryParameters:
        q1: string
      headers:
        h1:
          type: integer
          multipleOf: 2
          minimum: 2
      responses:
        200:


    settings:
      authorizationUri: http:/auth.com
      accessTokenUri: http://accessToken.com
      authorizationGrants: [ authorization_code ]

/resource:
  get:
    securedBy: [ obasic, * ]
