#%RAML 1.0 Extension
extends: /extension.raml
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/3085e0bc-0903-4ac0-af27-b30abcd68545/ # 
title: Hello World
version: v1
documentation:
  - title: Test From RAML
    content: |
      This is something from the RAML specification.

      Here is a link to [google](https://www.google.com)


/items:
  /{items}:
    get:
    head:





  