#%RAML 1.0

title: test API
types:
  airport:
    type: object
    properties:
      aircraft:
        type: array
        items: string
        uniqueItems: false
        minItems: 2
        maxItems: 4
