#%RAML 1.0

title: aaa

annotationTypes:
  One:
    type: object
    properties:
        aaa: string

  Two: number

(T*):
/afafasdfsdf:

  get:
    responses:
      200:
        body:
          application/json:
            type: object
