#%RAML 1.0
title: test1
types:

  Account:
    properties:
      label?:
        type: string
        description: display name of account
      owners?:
        type: string[]
        description: list of account owners

/accounts/aggregate:
  /{text}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Account[]
              examples:
                output: |
                         [*
                           {
                             "label": "Checking account",
                             "owners": ["John Wick", "Johhny"]
                           }
                          ]
