#%RAML 1.0 Trait

description: trait
queryParameters:
  param1:
    type: number
    description: Limit in the response list
    maximum: 300
    minimum: 1
    example: 100
    default: 25
  param2:
    type: number
    description: The start entry of the list
    minimum: 0
    example: 25
    default: 0
  param3:
    type: string
    description: |
      The `nextPageToken` is a web safe encoded cursor to the next entry in the database.
      It can be obtained by requesting paginated resource and used in next request to get
      next results page.
    pattern: "[a-zA-Z0-9]+"