#%RAML 1.0

title: test API
types:
  airplane:
    type: object
    xml:
      attribute: true # serialize it as an XML attribute
      name: "fullname"
      wrapped: true
      namespace: "air"
      prefix: "air"
    
