package org.mulesoft.amfintegration.vocabularies.propertyterms.patched.oaslike.oas3

import org.mulesoft.amfintegration.vocabularies.propertyterms.patched.oaslike.OaslikePathsKeyTerm

object Oas3PathsKeyTerm extends Oas3PatchedKeyTerm with OaslikePathsKeyTerm
