package org.mulesoft.amfintegration.vocabularies.propertyterms.patched.oaslike.oas2

import org.mulesoft.amfintegration.vocabularies.propertyterms.patched.oaslike.OaslikePathsKeyTerm

object Oas2PathsKeyTerm extends OaslikePathsKeyTerm with Oas2PatchedKeyTerm
