#%RAML 1.0
title: API
/someChildUri:
  uriParameters:
  post:
    responses:
      200:
        body:
          application/json:
          application/xml:
            (ex):
            properties:
              a:
            description: some very useful resource