#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: datetime
    format: rfc3339
types:
  airport:
    type: datetime
    format: rfc3339
annotationTypes:
  airport:
    type: datetime
    format: rfc3339
/resource/{airplane}:
  uriParameters:
    airplane:
      type: datetime
      format: rfc3339
  post:
    queryParameters:
      airplane:
        type: datetime
        format: rfc3339
    headers:
      A-IM:
        type: datetime
        format: rfc3339
    body:
      type: datetime
      format: rfc3339
    responses:
      201:
        body: airport
