#%RAML 1.0 Library 
types:
  lib1v1: !include enddt1.raml
  lib1v2: !include enddt2.raml
  lib1v3: !include enddt3.raml
  lib1v4: !include enddt4.raml
  lib1v5: !include enddt5.raml
  lib1v6: !include enddt6.raml
  lib1v7: !include enddt7.raml
  lib1v8: !include enddt8.raml
  lib1v9: !include enddt9.raml
  lib1v10: !include enddt10.raml