#%RAML 1.0 Library
uses:
  lib14v1: lib1.raml
  lib14v2: lib2.raml
  lib14v3: lib3.raml
  lib14v4: lib4.raml
  lib14v5: lib5.raml
  lib14v6: lib6.raml
  lib14v7: lib7.raml
  lib14v8: lib8.raml
  lib14v9: lib9.raml
  lib14v10: lib10.raml
  lib14v11: lib11.raml
  lib14v12: lib12.raml
  lib14v13: lib13.raml
