#%RAML 1.0 Library
uses:
  lib16v1: lib1.raml
  lib16v2: lib2.raml
  lib16v3: lib3.raml
  lib16v4: lib4.raml
  lib16v5: lib5.raml
  lib16v6: lib6.raml
  lib16v7: lib7.raml
  lib16v8: lib8.raml
  lib16v9: lib9.raml
  lib16v10: lib10.raml
  lib16v11: lib11.raml
  lib16v12: lib12.raml
  lib16v13: lib13.raml
  lib16v14: lib14.raml
  lib16v15: lib15.raml