#%RAML 1.0 Library
uses:
  lib13v1: lib1.raml
  lib13v2: lib2.raml
  lib13v3: lib3.raml
  lib13v4: lib4.raml
  lib13v5: lib5.raml
  lib13v6: lib6.raml
  lib13v7: lib7.raml
  lib13v8: lib8.raml
  lib13v9: lib9.raml
  lib13v10: lib10.raml
  lib13v11: lib11.raml
  lib13v12: lib12.raml
