#%RAML 1.0 Library
uses:
  lib17v1: lib1.raml
  lib17v2: lib2.raml
  lib17v3: lib3.raml
  lib17v4: lib4.raml
  lib17v5: lib5.raml
  lib17v6: lib6.raml
  lib17v7: lib7.raml
  lib17v8: lib8.raml
  lib17v9: lib9.raml
  lib17v10: lib10.raml
  lib17v11: lib11.raml
  lib17v12: lib12.raml
  lib17v13: lib13.raml
  lib17v14: lib14.raml
  lib17v15: lib15.raml
  lib17v16: lib16.raml