#%RAML 1.0 Library
uses:
  lib10v1: lib1.raml
  lib10v2: lib2.raml
  lib10v3: lib3.raml
  lib10v4: lib4.raml
  lib10v5: lib5.raml
  lib10v6: lib6.raml
  lib10v7: lib7.raml
  lib10v8: lib8.raml
  lib10v9: lib9.raml
