#%RAML 1.0 Library
uses:
  lib11v1: lib1.raml
  lib11v2: lib2.raml
  lib11v3: lib3.raml
  lib11v4: lib4.raml
  lib11v5: lib5.raml
  lib11v6: lib6.raml
  lib11v7: lib7.raml
  lib11v8: lib8.raml
  lib11v9: lib9.raml
  lib11v10: lib10.raml
