#%RAML 1.0 Library
uses:
  lib12v1: lib1.raml
  lib12v2: lib2.raml
  lib12v3: lib3.raml
  lib12v4: lib4.raml
  lib12v5: lib5.raml
  lib12v6: lib6.raml
  lib12v7: lib7.raml
  lib12v8: lib8.raml
  lib12v9: lib9.raml
  lib12v10: lib10.raml
  lib12v11: lib11.raml
