#%RAML 1.0 Library
uses:
  lib19v1: lib1.raml
  lib19v2: lib2.raml
  lib19v3: lib3.raml
  lib19v4: lib4.raml
  lib19v5: lib5.raml
  lib19v6: lib6.raml
  lib19v7: lib7.raml
  lib19v8: lib8.raml
  lib19v9: lib9.raml
  lib19v10: lib10.raml
  lib19v11: lib11.raml
  lib19v12: lib12.raml
  lib19v13: lib13.raml
  lib19v14: lib14.raml
  lib19v15: lib15.raml
  lib19v16: lib16.raml
  lib19v17: lib17.raml
  lib19v18: lib18.raml