#%RAML 1.0 Library
uses:
  lib18v1: lib1.raml
  lib18v2: lib2.raml
  lib18v3: lib3.raml
  lib18v4: lib4.raml
  lib18v5: lib5.raml
  lib18v6: lib6.raml
  lib18v7: lib7.raml
  lib18v8: lib8.raml
  lib18v9: lib9.raml
  lib18v10: lib10.raml
  lib18v11: lib11.raml
  lib18v12: lib12.raml
  lib18v13: lib13.raml
  lib18v14: lib14.raml
  lib18v15: lib15.raml
  lib18v16: lib16.raml
  lib18v17: lib17.raml