#%RAML 1.0 Library
uses:
  lib15v1: lib1.raml
  lib15v2: lib2.raml
  lib15v3: lib3.raml
  lib15v4: lib4.raml
  lib15v5: lib5.raml
  lib15v6: lib6.raml
  lib15v7: lib7.raml
  lib15v8: lib8.raml
  lib15v9: lib9.raml
  lib15v10: lib10.raml
  lib15v11: lib11.raml
  lib15v12: lib12.raml
  lib15v13: lib13.raml
  lib15v14: lib14.raml