#%RAML 1.0 Library
uses:
  lib20v1: lib1.raml
  lib20v2: lib2.raml
  lib20v3: lib3.raml
  lib20v4: lib4.raml
  lib20v5: lib5.raml
  lib20v6: lib6.raml
  lib20v7: lib7.raml
  lib20v8: lib8.raml
  lib20v9: lib9.raml
  lib20v10: lib10.raml
  lib20v11: lib11.raml
  lib20v12: lib12.raml
  lib20v13: lib13.raml
  lib20v14: lib14.raml
  lib20v15: lib15.raml
  lib20v16: lib16.raml
  lib20v17: lib17.raml
  lib20v18: lib18.raml
  lib20v19: lib19.raml