#%RAML 1.0
title: test
mediaType: application/json

uses:
  r1: lib1.raml # 12 
  r2: lib2.raml # 34
  r3: lib3.raml # 78
  r4: lib4.raml # 166
  r5: lib5.raml # 332
  r6: lib6.raml # 664
  r7: lib7.raml # 1328
  r8: lib8.raml # 2656 calls
  r9: lib9.raml # 5312 calls
  r10: lib10.raml # 10624 calls
  r11: lib11.raml # 21248 calls
  r12: lib12.raml # 42496 calls
  r13: lib13.raml # 84992 calls
  r14: lib14.raml # 169984 calls
  r15: lib15.raml # 169984 calls
  r16: lib16.raml
  r17: lib17.raml
  r18: lib18.raml
  r19: lib19.raml
  r20: lib20.raml

#
