#%RAML 1.0
title: test
types:
  CustomDate:
    facets:
      onlyFutureDates?: boolean
      noHolidays: boolean
  AnotherDate:
    type: CustomDate
    facets:
      aNewFacet: boolean
  PossibleMeetingDate:
    type: AnotherDate
    *