#%RAML 1.0
title: test
types:
  NewTestType:
    type: object
    properties:
      field: string
    example:
      field: value
resourceTypes:
  TestResorceType:
    post:
      description: Allows to create new <<objectName | !singularize>>
      body:
        application/json:
          type: New<<objectName | !singularize>>
/resource:
  type:  { TestResorceType: {objectName : TestType} }
