#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: airplane
types:
  airplane:
    properties:
      count: number
      length: number
    minProperties: 1
    maxProperties: 2
    additionalProperties: false
/resource/{airplane}:
  uriParameters:
    airplane:
      properties:
        count: number
        length: number
      minProperties: 1
      maxProperties: 2
      additionalProperties: false
  post:
    queryParameters:
      airplane:
        properties:
          count: number
          length: number
        minProperties: 1
        maxProperties: 2
        additionalProperties: false
    headers:
      A-IM:
        properties:
          count: number
          length: number
        minProperties: 1
        maxProperties: 2
        additionalProperties: false
