#%RAML 1.0
title: Example API

resourceTypes:
  searchableCollection:
    get:
      queryParameters:
        <<queryParamName>>:
          description: Return <<resourcePathName>> that have their <<queryParamName>> matching the given value

traits:
  RENAMED:
    queryParameters:
      <<tokenName>>:
        description: A valid <<tokenName>> is required

/books:
  type: { searchableCollection: { queryParamName: title } }
  get:
    is: [ { RENAMED: { tokenName: access_token } }]
