#%RAML 1.0
title: API with Types
types:
  union:
    type: object | PossibleMeetingDate
  PossibleMeetingDate:
    type: CustomDate
    noHolidays: true
    facets:
      noHobby: boolean
  CustomDate:
    type: date-only
    facets:
      onlyFutureDates?: boolean # optional  in `PossibleMeetingDate`
      noHolidays: boolean # required in `PossibleMeetingDate`
