#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com
documentation:
 - title: Getting Started
   content: github-3-getting-started.md
 - title: Basics of Authentication
   content: github-3-basics-of-authentication.md
 - title: Rendering Data as Graphs
   cont*ent: !include doc.md
