#%RAML 1.0 SecurityScheme
description: ""
type: OAuth 2.0
describedBy: 
  headers: 
    Authorization: 
      description: |
        Used to send a valid OAuth 2 access token. The token must be preceeded by the word "Bearer".
      example: Bearer _token_
settings: 
  authorizationUri: https://login.salesforce.com/services/oauth2/authorize
  accessTokenUri: https://login.salesforce.com/services/oauth2/token
  authorizationGrants: [ authorization_code ]