#%RAML 0.8
title: Parameter
/res:
  get:
    queryParameters:
      param:
        displayName: parameter1
        description: parameter description
        default: abc
        required: true
        example: cba
        pattern: "*"
        minLength: 2
        maxLength: 6
        enum: [abc, cba]
