#%RAML 1.0
title: tst
types:
  tt:
    type: array
    items:
      type: abc
      properties:
        bc: string
        mb: boolean
  arr:
    type: object
  abc:
    type: object
    properties:
      aa: string
      bb: boolean
  bb:
    type: object
