#%RAML 1.0
title: tst
types:
  tt:
    type: array
    items: arr
  arr:
    type: [abc , bb]
  abc:
    type: object
    properties:
      abc: string
  bb:
    type: object
    properties:
      efg: boolean
