#%RAML 1.0
title: tst
types:
  tt:
    type: array
    items: abc
  arr:
    type: object
  abc:
    type: object
    properties:
      aa: string
      bb?: boolean
      cc: number
  bb:
    type: object
