#%RAML 1.0
title: test
types:
  A:
      type: object
      properties:
        prop: string
      example:
        prop: this is an example
  Person:
    type: !include aux/person.json
    description: my schema
  Board:
    properties:
      members: Person[]
    description: board of directors
/payload:
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              aString: string
              myObject: A
            example: !include aux/example.json
    body:
      application/json:
        type: object
        properties:
          numberHolder:
            type: object
            properties:
              min:
                type: !include aux/mySchema.json
              max: number
            example:
              max: 9
              min: "test"