#%RAML 1.0
title: test
types:
  Person: |
          {
            "$id": "https://example.com/person.schema.json",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "Person",
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string",
                "description": "The person's first name."
              },
              "lastName": {
                "type": "string",
                "description": "The person's last name."
              },
              "age": {
                "description": "Age in years which must be equal to or greater than zero.",
                "type": "integer",
                "minimum": 0
              }
            }
          }
  DisabledOnInherited:
    type: Person
    properties:
      myProp:
        type: External
      scalarProp:
        type: string
    description: action should be disabled on this node
/path:
  get:
    description: get a path
    responses:
      200:
        body:
          application/json: |
            {
              "$id": "https://example.com/arrays.schema.json",
              "$schema": "http://json-schema.org/draft-07/schema#",
              "description": "A representation of a person, company, organization, or place",
              "type": "object",
              "properties": {
                "fruits": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "vegetables": {
                  "type": "array",
                  "items": { "$ref": "#/definitions/veggie" }
                }
              },
              "definitions": {
                "veggie": {
                  "type": "object",
                  "required": [ "veggieName", "veggieLike" ],
                  "properties": {
                    "veggieName": {
                      "type": "string",
                      "description": "The name of the vegetable."
                    },
                    "veggieLike": {
                      "type": "boolean",
                      "description": "Do I like this vegetable?"
                    }
                  }
                }
              }
            }