addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.32")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.6.1")
addSbtPlugin("com.github.mwz"     % "sbt-sonar"                % "2.1.0")
addSbtPlugin("com.eed3si9n"       % "sbt-sriracha"             % "0.1.0")
