#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/bd3eebef-bc18-4386-b17f-c67576ca2054 # baseUri:
description: Спецификация REST API проекта "Победа ТГО"

securitySchemes:

/access-tokens:
  displayName: Авторизация, токен
  description:
  post:
    responses:
      200:
        body:
          example:
            {
              "accessToken":"12hk3h1k231h2k312k3h3332",
              "apiVersion":"1.0.11"
            }