#%RAML 1.0
title: Test API
/endpoint1:
  get:
    queryParameters:
      a:
       type: string
/endpoint2:
  get:
    body:
      application/json:
        type: string
/endpoint3:
  post:
    body:
      application/json:
        type: string
.
.
/endpoint4:
  get:
    body:
      type: st