#%RAML 1.0
types:
  A:
    type: array


  newtype:
    type: object
    properties:
      a:
        type: string
      b:
        type: integer
title: test

/endpoint:
  get:
    responses:
      200:
        body:
            application/json:
              type: newtype
