#%RAML 1.0
/test:
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
                name: string
            example:
                na[*]me: ex