#%RAML 1.0

types:
  newtype:
    type: object
    properties:
      name:
        type: string
/test:
  get:
    responses:
      200:
        body:
          application/json:
            type: newtype
