#%RAML 1.0
title: test
/test:
  get:
    responses:
      200:
        body:
          application/json:
            type: newtype
version: 1
types:
  newtype:
    type: object
    properties:
      name:
        type: string
