#%RAML 1.0
title: tst
types:
  arr:
    type: array
  abc:
    type: object
    displayName: cba
    description: aoeu
    example:
      aa: aoeu
      cc: 4
    properties:
      aa: string
      bb?: boolean
      cc: number
  bb:
    type: array
    items: string
