#%RAML 1.0
title: API
securitySchemes:
  oauth:
    type: OAuth 1.0
    settings:
      requestTokenUri: uri
      authorizationUri: uri
      tokenCredentialsUri: uri
      signatures: [HMAC-SHA1, RSA-SHA1, PLAINTEXT]
    describedBy:
      queryParameters:
        abc: number
      headers:
        If-Match:
      responses:
        200:
        201:
