#%RAML 1.0
title: tst
types:
  t2:
    type: object
    properties:
      b: abc
  arr:
    type: object
  abc:
    type: object
    properties:
      aa: string
      bb?: boolean
      cc: number
  bb:
    type: object
