#%RAML 1.0
title: test API

resourceTypes:
  resourceType1:
    description: <<param1>>
    post:
      description: <<param2>>
  resourceType2:
    description: <<param1>>
    get:
      description: <<param2>>

/resource:
  type: res*