#%RAML 1.0

title: test API
mediaType: application/json
types:
  airplane:
    type: string
    pattern: [abc]
    minLength: 2
    maxLength: 6
    enum: [abc]
/resource:
  post:
    body:
      type: string
      pattern: [abc]
      minLength: 2
      maxLength: 6
      enum: [abc]
    responses:
      201:
        body: airplane
