#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: boolean
types:
  airport:
    properties:
      item:
        type: boolean

