#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: datetime
    format: rfc3339
types:
  airport:
    properties:
      item:
        type: datetime
        format: rfc3339
