#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: number
    minimum: 2
    maximum: 6
    format: int32
    multipleOf: 2
    enum: [2,4]
types:
  airplane:
    type: number
    minimum: 2
    maximum: 6
    format: int32
    multipleOf: 2
    enum: [2,4]
/resource/{airplane}:
  uriParameters:
    airplane:
      type: number
      minimum: 2
      maximum: 6
      format: int32
      multipleOf: 2
      enum: [2,4]
  post:
    queryParameters:
      airplane:
        type: number
        minimum: 2
        maximum: 6
        format: int32
        multipleOf: 2
        enum: [2,4]
    headers:
      A-IM:
        type: number
        minimum: 2
        maximum: 6
        format: int32
        multipleOf: 2
        enum: [2,4]
