#%RAML 1.0
title: ALS-1227

traits:
  secured:
    queryParameters:
      <<tokenName>>:
        descri*ption: A valid <<tokenName>> is required

/books:
  get:
    is: [ {secured: {tokenName: access_token}}]
