#%RAML 1.0
title: ConsoleExamplesTest
uses:
  myTypes: types1.raml
  myTypes2: types2.raml
/testExamples:
  get:
    responses:
      200:
        body:
          application/json:
            type: myTypes2.*