#%RAML 0.8
title: test
schemas:
  - NewSchema: |
          {
                "$schema": "http://json-schema.org/draft-03/schema",
                "properties": {
                    "input": {
                        "required": false,
                        "type": "string"
                    }
                },
                "required": false,
                "type": "object"
              }
resourceTypes:
  - TestResorceType:
      post:
        description: Allows to create new <<objectName | !singularize>>
        body:
          application/json:
            schema: New<<objectName | !singularize>>
/resource:
  type:  { TestResorceType: {objectName: Schema} }
