#%RAML 1.0
types:
    a:
        type: object
        properties:
            b: string
            c: string
            d: string
    ar:
        type: array
        items:
            type: a
        example: [b, *]