#%RAML 1.0
title: test

types:
  AnotherType:
    properties:
      valueOne: string
      valueTwo: number
      valueThree:
        properties:
              valueFour: string
              valueFive: string
              value:
                properties:
                  valueSeven: string
                  valueEight: boolean
    example:
      valueThree:
        value:
          value*