# %RAML 1.0
title: t
version: 1
types:
    t:
      type: string
        example: ex
    non-error-type: 
      type: object
      properties: 
        name: string
                        # Comment          
        dni: number
        optional: 
          type: object
          required: false
          properties: 
            val: string