#%RAML 1.0
title: test API

resourceTypes:
  resourceType1:
    description: <<param1>>
    post:
      description: <<param2>>
  resourceType2:
    description: <<param3>>
    get:
      description: <<param4>>

/resource:
  type:
    resourceType1:
      *
    resourceType2:

/res2: