#%RAML 1.0
title: tst
types:
  t2:
    type: object
    properties:
      b: arr
  arr:
    type: [abc , bb]
  abc:
    type: object
    properties:
      abc: string
  bb:
    type: object
    properties:
      efg: boolean
