#%RAML 1.0

title: test API
mediaType: application/json
types:
  airplane:
    type: file
    fileTypes:
      - zip
      - rar
      - 7z
    minLength: 100
    maxLength: 1000
/resource:
  post:
    body:
      type: file
      fileTypes:
        - zip
        - rar
        - 7z
      minLength: 100
      maxLength: 1000
    responses:
      201:
        body: airplane
