#%RAML 1.0

title: test API
types:
  airport:
    type: object
    properties:
      aircraft:
        type: file
        fileTypes:
          - zip
          - rar
          - 7z
        minLength: 100
        maxLength: 1000
