#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: airplane
types:
  airplane:
    type: file
    fileTypes:
      - zip
      - rar
      - 7z
    minLength: 100
    maxLength: 1000
/resource/{airplane}:
  uriParameters:
    airplane:
      type: file
      fileTypes:
        - zip
        - rar
        - 7z
      minLength: 100
      maxLength: 1000
  post:
    queryParameters:
      airplane:
        type: file
        fileTypes:
          - zip
          - rar
          - 7z
        minLength: 100
        maxLength: 1000
    headers:
      A-IM:
        type: file
        fileTypes:
          - zip
          - rar
          - 7z
        minLength: 100
        maxLength: 1000
