#%RAML 1.0

title: test API
mediaType: application/json
types:
  airplane:
    type: number
    minimum: 2
    maximum: 6
    format: int32
    multipleOf: 2
    enum: [2,4]
/resource:
  post:
    body:
      type: number
      minimum: 2
      maximum: 6
      format: int32
      multipleOf: 2
      enum: [2,4]
    responses:
      201:
        body: airplane
