#%RAML 1.0
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securitySchemes:
  bas*ic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
