#%RAML 1.0 DataType
type: object
properties: 
  transactionID: string
  fromAccount: !include Account.raml
  transactionType: 
    enum: 
      - atm 
      - deposit 
      - cashWithdrawal
      - sepa
      - online
  transactionName?: string
  postedAt: datetime
  completedAt?: datetime