#%RAML 1.0

title: test API
mediaType: application/json
baseUri: www.{domain}/{airplane}
baseUriParameters:
  airplane:
    type: boolean
    enum: [true, false]
types:
  airport:
    type: boolean
    enum: [true, false]
annotationTypes:
  airport:
    type: boolean
    enum: [true, false]
/resource/{airplane}:
  uriParameters:
    airplane:
      type: boolean
      enum: [true, false]
  post:
    queryParameters:
      airplane:
        type: boolean
        enum: [true, false]
    headers:
      A-IM:
        type: boolean
        enum: [true, false]
    body:
      type: boolean
      enum: [true, false]
    responses:
      201:
        body: airport
