#%RAML 1.0
title: GitHub API

securitySchemes: 
  basic: 
    type: Basic Authentication
  oauth_1_0:
    type: OAuth 1.0
  oauth_2_0:
    type: OAuth 2.0

/users/{userid}/gists: 
  get: 
    securedBy: 
      - *