#%RAML 1.0

title: aaa

annotationTypes:
  AOne:
    type: object
    properties:
        aaa: string

  ATwo: number

/afafasdfsdf:

  get:
    *
    responses:
      200:
        body:
          application/json:
            type: object
