#%RAML 1.0
title: My API With Types
/users/{id}:
  ge*t:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              firstname:
                type: string
              lastname:
                type: string
              age:
                type: number
