#%RAML 1.0

securitySchemes:
  test:
    type: Basic Authentication

title: API
description: a description
version: 1.0
baseUri: /some/base/uri
securedBy:
  - test
protocols:
  - HTTP

documentation:
  - title: oneDoc
    content: bla
  - title: twoDoc
    content: bla2


/someChildUri:
  get:

