#%RAML 1.0
title: test API
#usage: test library
description: test mapping API
baseUri: https://www.example.com/{version}/{param1}/{param2}
version: 1.0
protocols:
  - HTTP
  - HTTPS

mediaType: [ application/json, application/xml ]

securedBy: [ BASIC, OAUTH20 ]

documentation:


baseUriParameters:
  param1:
  param2:
  param3:

(AnnotationType1): some string value
(AnnotationType2): another string value
types:
  MyType:
    (MissingAnnotation): stringValue
    properties:
      p1: NonExistingType
      p2:
  MyType1:

traits:
  Trait1:
  Trait2:

annotationTypes:
  AnnotationType1:
  AnnotationType2:

resourceTypes:
  ResourceType1:
  ResourceType2:

securitySchemes:
  OAUTH20:
    type: OAuth 2.0
  BASIC:
    type: Basic Authentication

/resource1:
  get:
    responses:
      200:
        body:
          application/json:
  /subresource1:
    delete:

/resource2:
  post:
  put:

documentation:
  - title: blah
    content: blah blah 3
  - title: docItem1
    value: some text content