#%RAML 1.0 DataType
type: string
x
example: |
            Lorem ipsum dolor sit amet consectetur adipiscing elit tristique ligula eu sed vestibulum dignissim, quisque nisi torquent cursus vulputate mattis etiam cras consequat molestie iaculis. Tellus blandit rutrum hendrerit quis maecenas est, vitae lacus leo netus felis volutpat suspendisse, integer primis gravida tristique dictumst. Ornare rhoncus hendrerit lobortis tristique turpis eros, vitae per erat quam nibh lectus viverra, odio lacus enim ligula vivamus.
            Fringilla sapien blandit nisi fusce curabitur odio pretium sollicitudin nulla curae morbi, a facilisi placerat venenatis sed feugiat gravida ad vitae commodo, vel dui primis euismod tellus facilisis quis vestibulum porttitor orci. Vestibulum nunc massa suspendisse semper per ac venenatis erat, orci dignissim diam habitasse taciti augue tincidunt tempus, sociosqu aptent rhoncus eros aliquam etiam eu. Facilisi felis torquent condimentum ullamcorper tempor elementum velit sociosqu inceptos, quisque dis habitant dictumst morbi metus aliquet class, eleifend nec blandit nunc lacus neque cursus mauris.


