#%RAML 0.8
title: ALS-1539
securitySchemes:
  RENAMED:
    type: OAuth 2.0
    description: test
    settings:
      scopes:
        - ADMINISTRATOR
/users/{userid}/test:
  get:
    securedBy: [null, {RENAMED: {scopes: [ADMINISTRATOR]}}]