#%RAML 1.0
title: API
securitySchemes:
  oauth:
    type: OAuth 2.0
    describedBy:
      queryParameters:
        abc: number
      headers:
        If-Match:
      responses:
        200:
        201:
