#%RAML 1.0
title: test

types:
  ExtendedString:
    type: string
    facets:
      testFacet1: boolean
      testFacet2: string

  AAA:
    type: BBB
  BBB:
    facets:
      testFacet3: object

  CCC:
    type: object
    facets:
      testFacet4: object

  TestType:
    type: [ExtendedString, AAA]

    facets:
      testFacet5: number
    t*

