#%RAML 1.0 Library

uses:
  FHIR_commons: /exchange_modules/org.mule.templates/fhir-commons/1.0.0/fhir_commons.raml

types:
  Entry:
    type: FHIR_commons.BackboneElement
    properties:
      link?:
        type: array
        items:
          type: FHIR_commons.BackboneElement
          properties:
            relation: string
            url: FHIR_commons.uri
      fullUrl?: FHIR_commons.uri
      search?:
        type: FHIR_commons.BackboneElement
        properties:
          mode?:
            type: FHIR_commons.code
            enum: [match, include, outcome]
          score?: FHIR_commons.decimal
      request?:
        type: FHIR_commons.BackboneElement
        properties:
          method:
            type: FHIR_commons.code
            enum: [GET, PUT, POST, DELETE]
          url: FHIR_commons.uri
          ifNoneMatch?: string
          ifModifiedSince?: FHIR_commons.instant
          ifMatch: string
          ifNoneExist: string
      response?:
        type: object
        properties:
          status: string
          location?: FHIR_commons.uri
          etag?: string
          lastModified?: FHIR_commons.instant

  DeviceEntry:
    type: Entry
    properties:
      resource?: !include /exchange_modules/org.mule.templates/device/1.0.0/device.raml

  ObservationEntry:
    type: Entry
    properties:
       resource?: !include /exchange_modules/org.mule.templates/observation/1.0.0/observation.raml