#%RAML 1.0 Library

uses:
  FHIR_entry_types: ./fhir_entry_types.raml
  FHIR_commons: /exchange_modules/org.mule.templates/fhir-commons/1.0.0/fhir_commons.raml

types:
  Resource: FHIR_commons.Resource

  Bundle:
    type: Resource
    properties:
      resourceType?: string
      type:
        type: FHIR_commons.code
        enum: [document, message, transaction,  transaction-response, batch, batch-response,  history, searchset, collection]
      total?: FHIR_commons.unsignedInt
      link?:
        type: array
        items:
          type: FHIR_commons.BackboneElement
          properties:
            relation: string
            url: FHIR_commons.uri
      signature?: FHIR_commons.Signature

  DeviceBundle:
    type: Bundle
    properties:
      entry?: FHIR_entry_types.DeviceEntry[]

  ObservationBundle:
    type: Bundle
    properties:
      entry?: FHIR_entry_types.ObservationEntry[]