#%RAML 1.0
title: test

annotationTypes:
  annToDelete:
    type: string

types:
  typeToDelete:
    type: string

resourceTypes:
  toDeleteR2:
    description: an endpoint
    post:
      body:

traits:
  toDeleteTr:
    description: a trait
    body:

securitySchemes:
  s2ToDelete:
    description: gonna deletee
    type: Digest Authentication

